spark2014:
        vcs: git
        url: https://github.com/kanigsson/spark2014.git
        revision: myfsf
why3:
        vcs: git
        url: https://github.com/kanigsson/why3.git
        revision: myfsf
alt-ergo:
        vcs: git
        url: https://github.com/kanigsson/alt-ergo.git
        revision: myfsf
