name = "gnatprove"
version = "16.0.0-20251202"
authors = ["AdaCore"]
description = "Automatic formal verification of SPARK code"
maintainers = ["Fabien Chouteau <chouteau@adacore.com>", "César Sagaert <sagaert@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau", "AldanTanneo"]
licenses = "GPL-3.0-or-later"
website = "https://docs.adacore.com/spark2014-docs/html/ug/index.html"

long-description = """
GNATprove, which provides automatic formal verification of SPARK code, is based on the [open-source](https://github.com/AdaCore/spark2014) [SPARK Pro](https://www.adacore.com/sparkpro) by [AdaCore](https://www.adacore.com).
The [SPARK Pro User's Guide](https://docs.adacore.com/spark2014-docs/html/ug/index.html) provides extensive documentation on how to use GNATprove.
Note that because this version of GNATprove is built from an intermediate commit of SPARK Pro, it is not representative of any specific SPARK Pro release, and the SPARK Pro documentation may describe features or capabilities that are not yet available in this version of GNATprove.

To use GNATprove, simply add it to your Alire project using

    alr with gnatprove

Then, configure your environment by running:

    eval "$( alr printenv )"

You will then be able to run GNATprove:

    gnatprove

For more details on getting started using GNATprove, see [Getting Started with SPARK](https://docs.adacore.com/spark2014-docs/html/ug/en/getting_started.html) from the [SPARK Pro User's Guide](https://docs.adacore.com/spark2014-docs/html/ug/index.html).

To get started with the SPARK language, see the [Introduction to SPARK](https://learn.adacore.com/courses/intro-to-spark/index.html) course on [learn.adacore.com](https://learn.adacore.com/index.html).
"""

auto-gpr-with = false

[configuration]
disabled = true

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"
GPR_PROJECT_PATH.prepend = "${CRATE_ROOT}/lib/gnat"


[origin."case(os)".linux."case(host-arch)".x86-64]
binary = true
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-16.0.0-snapshot/gnatprove-x86_64-linux-16.0.0-20251202.tar.gz"
hashes = ["sha256:26d10957adcff5fc06d1384e0735629988169137b6f625626f6abe254bf1dbcf"]


[origin."case(os)".linux."case(host-arch)".aarch64]
binary = true
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-16.0.0-snapshot/gnatprove-aarch64-linux-16.0.0-20251202.tar.gz"
hashes = ["sha256:805667c8cdd2abc356a3bc2e8cb653483f4ac96cd8ca1aecc4a13b31d121127c"]


[origin."case(os)".macos."case(host-arch)".x86-64]
binary = true
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-16.0.0-snapshot/gnatprove-x86_64-darwin-16.0.0-20251202.tar.gz"
hashes = ["sha256:3edc64c58771ddab9d67c315cdde5a962f5f8750371db51fc788aced38bbfc9d"]


[origin."case(os)".macos."case(host-arch)".aarch64]
binary = true
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-16.0.0-snapshot/gnatprove-aarch64-darwin-16.0.0-20251202.tar.gz"
hashes = ["sha256:6d7a40d2f1440796557cd67e8a6198c83ea6a8c01ca2e1ef154e6b2662be4e26"]


[origin."case(os)".windows."case(host-arch)".x86-64]
binary = true
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-16.0.0-snapshot/gnatprove-x86_64-windows64-16.0.0-20251202.tar.gz"
hashes = ["sha256:230eed3a3d054683fa5f1744ca33cae457b60ada2b8c2a1098bbb2313a79ca2a"]
