name = "gnat_native"
version = "16.1.1-20260704"
provides = ["gnat=16.1.1-20260704"]
description = "The GNAT Ada compiler - Native"
maintainers = ["Fabien Chouteau <chouteau@adacore.com>", "César Sagaert <sagaert@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau", "AldanTanneo"]
licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"
website = "https://github.com/alire-project/GNAT-FSF-builds"

auto-gpr-with = false

[configuration]
disabled = true

[environment."case(os)".linux]
PATH.prepend = "${CRATE_ROOT}/bin"
LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib64"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib64"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/lib64"

[environment."case(os)".windows."case(host-arch)".x86-64]
PATH.prepend = "${CRATE_ROOT}/bin"
LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/lib"

[environment."case(os)".macos]
PATH.prepend = "${CRATE_ROOT}/bin"
LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/lib"


[origin."case(os)".linux."case(host-arch)".x86-64]
binary = true
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-16.1.1-snapshot/gnat-x86_64-linux-16.1.1-20260704.tar.gz"
hashes = ["sha256:ba9c1e4ec1f583e69277fcfe1687b10424dfcd90b95ccf5b8f8212b32bb72379"]


[origin."case(os)".linux."case(host-arch)".aarch64]
binary = true
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-16.1.1-snapshot/gnat-aarch64-linux-16.1.1-20260704.tar.gz"
hashes = ["sha256:79e200ff2f98a250d4e00a77034b31283fae501846e18976c6da43ca2b17b6d8"]


[origin."case(os)".macos."case(host-arch)".x86-64]
binary = true
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-16.1.1-snapshot/gnat-x86_64-darwin-16.1.1-20260704.tar.gz"
hashes = ["sha256:af53ecefd7ded69d43f1159c27bc7bd75ae0351117bcd01920fb3e0e73eb7dc1"]


[origin."case(os)".macos."case(host-arch)".aarch64]
binary = true
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-16.1.1-snapshot/gnat-aarch64-darwin-16.1.1-20260704.tar.gz"
hashes = ["sha256:c5a4ee5af8ff1656546cfbd08882ea7db4d1d33c9ec0b0330cb3d8bef6d0724d"]
