name = "gnat_native"
version = "16.0.0-20260104"
provides = ["gnat=16.0.0-20260104"]
description = "The GNAT Ada compiler - Native"
maintainers = ["Fabien Chouteau <chouteau@adacore.com>", "César Sagaert <sagaert@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau", "AldanTanneo"]
licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"
website = "https://github.com/alire-project/GNAT-FSF-builds"

auto-gpr-with = false

[configuration]
disabled = true

[environment."case(os)".linux]
PATH.prepend = "${CRATE_ROOT}/bin"
LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib64"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib64"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/lib64"

[environment."case(os)".windows."case(host-arch)".x86-64]
PATH.prepend = "${CRATE_ROOT}/bin"
LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/lib"

[environment."case(os)".macos]
PATH.prepend = "${CRATE_ROOT}/bin"
LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/lib"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/lib"


[origin."case(os)".linux."case(host-arch)".x86-64]
binary = true
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-16.0.0-snapshot/gnat-x86_64-linux-16.0.0-20260104.tar.gz"
hashes = ["sha256:25862707174820a243842b2a2af106514ed6bc4fbb10b0487366e1d049f4bd1a"]


[origin."case(os)".linux."case(host-arch)".aarch64]
binary = true
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-16.0.0-snapshot/gnat-aarch64-linux-16.0.0-20260104.tar.gz"
hashes = ["sha256:8421f2e8fe8ae3b66ebffe4ce8dc06a0a73b96fcadb91269bf12199556ed7fbb"]


[origin."case(os)".macos."case(host-arch)".x86-64]
binary = true
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-16.0.0-snapshot/gnat-x86_64-darwin-16.0.0-20260104.tar.gz"
hashes = ["sha256:f866e2c7a191e8a89e2b4a4ed979cf1434db5089d766ea61404acc728967f8b4"]


[origin."case(os)".macos."case(host-arch)".aarch64]
binary = true
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-16.0.0-snapshot/gnat-aarch64-darwin-16.0.0-20260104.tar.gz"
hashes = ["sha256:e606e3d92c0859f8d14c209c120364a1171fa71e0d93be85fd720c7e8bf486ca"]
