name: GNAT FSF builds
'on':
  pull_request:
    paths-ignore:
    - generate/**
    - utils/**
    - LICENSE
    - README.md
    - .gitignore
  workflow_dispatch:
    inputs:
      do_gh_release:
        description: Set to true to publish results in a GitHub release
        type: boolean
        required: false
        default: false
jobs:
  gcc_dependencies_ubuntu-22-04:
    name: GCC Dependencies (ubuntu-22.04)
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Build GMP
      run: python3 ./anod build gmp -v --loglevel DEBUG --enable-cleanup
    - name: Build MPFR
      run: python3 ./anod build mpfr -v --loglevel DEBUG --enable-cleanup
    - name: Build MPC
      run: python3 ./anod build mpc -v --loglevel DEBUG --enable-cleanup
    - name: Build ISL
      run: python3 ./anod build isl -v --loglevel DEBUG --enable-cleanup
    - name: Upload artifact 'gcc-dependencies-artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: gcc-dependencies-artifacts_ubuntu-22-04
        path: out_artifacts/*
        retention-days: 1
  gnat_ubuntu-22-04:
    needs:
    - gcc_dependencies_ubuntu-22-04
    name: GNAT (ubuntu-22.04)
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gcc-dependencies-artifacts'
      uses: actions/download-artifact@v4
      with:
        name: gcc-dependencies-artifacts_ubuntu-22-04
        path: in_artifacts/
    - name: Build GNAT native
      run: python3 ./anod build gcc -v --loglevel DEBUG --enable-cleanup
    - name: Build GDB
      run: python3 ./anod build gdb -v --loglevel DEBUG --enable-cleanup
    - name: Package GNAT
      run: python3 ./anod build release_package --qualifier=package=gnat -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNAT
      run: python3 ./anod build release_github --qualifier=package=gnat -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnat-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnat-release-packages_ubuntu-22-04
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gprbuild_ubuntu-22-04:
    name: GPRbuild (ubuntu-22.04)
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Build GPRbuild
      run: python3 ./anod build gprbuild -v --loglevel DEBUG --enable-cleanup
    - name: Package GPRbuild
      run: python3 ./anod build release_package --qualifier=package=gprbuild -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GPRbuild
      run: python3 ./anod build release_github --qualifier=package=gprbuild -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gprbuild-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gprbuild-release-packages_ubuntu-22-04
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnat_cross_ubuntu-22-04:
    strategy:
      fail-fast: false
      matrix:
        target:
        - arm-elf
        - aarch64-elf
        - riscv64-elf
        - x86_64-elf
        - avr-elf
        - xtensa-esp32-elf
    needs:
    - gcc_dependencies_ubuntu-22-04
    name: GNAT Cross (ubuntu-22.04)
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gcc-dependencies-artifacts'
      uses: actions/download-artifact@v4
      with:
        name: gcc-dependencies-artifacts_ubuntu-22-04
        path: in_artifacts/
    - name: Build GNAT ${{ matrix.target }}
      run: python3 ./anod build gcc --target=${{ matrix.target }} -v --loglevel DEBUG --enable-cleanup
    - name: Build GDB ${{ matrix.target }}
      run: python3 ./anod build gdb --target=${{ matrix.target}} -v --loglevel DEBUG --enable-cleanup
    - name: Package GNAT ${{ matrix.target }}
      run: python3 ./anod build release_package --qualifier=package=gnat --target=${{ matrix.target }} -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNAT ${{ matrix.target }}
      run: python3 ./anod build release_github --qualifier=package=gnat --target=${{ matrix.target }} -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnat-release-packages-${{matrix.target}}'
      uses: actions/upload-artifact@v4
      with:
        name: gnat-release-packages-${{matrix.target}}_ubuntu-22-04
        path: sbx/*/release_package*/install/*
  spark_ubuntu-22-04:
    needs:
    - gprbuild_ubuntu-22-04
    name: SPARK (ubuntu-22.04)
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_ubuntu-22-04
        path: in_artifacts/
    - name: Build SPARK
      run: python3 ./anod build spark2014 -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATprove
      run: python3 ./anod build release_package --qualifier=package=gnatprove -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATprove
      run: python3 ./anod build release_github --qualifier=package=gnatprove -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatprove-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatprove-release-packages_ubuntu-22-04
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnatformat_ubuntu-22-04:
    needs:
    - gprbuild_ubuntu-22-04
    name: GNATformat (ubuntu-22.04)
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_ubuntu-22-04
        path: in_artifacts/
    - name: Build GNATformat
      run: python3 ./anod build gnatformat -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATformat
      run: python3 ./anod build release_package --qualifier=package=gnatformat -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATformat
      run: python3 ./anod build release_github --qualifier=package=gnatformat -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatformat-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatformat-release-packages_ubuntu-22-04
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnatdoc_ubuntu-22-04:
    needs:
    - gprbuild_ubuntu-22-04
    name: GNATdoc (ubuntu-22.04)
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_ubuntu-22-04
        path: in_artifacts/
    - name: Build GNATdoc
      run: python3 ./anod build gnatdoc -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATdoc
      run: python3 ./anod build release_package --qualifier=package=gnatdoc -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATdoc
      run: python3 ./anod build release_github --qualifier=package=gnatdoc -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatdoc-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatdoc-release-packages_ubuntu-22-04
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnattest_ubuntu-22-04:
    needs:
    - gprbuild_ubuntu-22-04
    name: GNATtest (ubuntu-22.04)
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_ubuntu-22-04
        path: in_artifacts/
    - name: Build GNATtest
      run: python3 ./anod build gnattest -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATtest
      run: python3 ./anod build release_package --qualifier=package=gnattest -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATtest
      run: python3 ./anod build release_github --qualifier=package=gnattest -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnattest-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnattest-release-packages_ubuntu-22-04
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnatcoverage_ubuntu-22-04:
    needs:
    - gprbuild_ubuntu-22-04
    name: GNATcoverage (ubuntu-22.04)
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_ubuntu-22-04
        path: in_artifacts/
    - name: Build GNATcoverage
      run: python3 ./anod build gnatcov -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATcoverage
      run: python3 ./anod build release_package --qualifier=package=gnatcov -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATcoverage
      run: python3 ./anod build release_github --qualifier=package=gnatcov -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatcov-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatcov-release-packages_ubuntu-22-04
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gcc_dependencies_ubuntu-22-04-arm:
    name: GCC Dependencies (ubuntu-22.04-arm)
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Build GMP
      run: python3 ./anod build gmp -v --loglevel DEBUG --enable-cleanup
    - name: Build MPFR
      run: python3 ./anod build mpfr -v --loglevel DEBUG --enable-cleanup
    - name: Build MPC
      run: python3 ./anod build mpc -v --loglevel DEBUG --enable-cleanup
    - name: Build ISL
      run: python3 ./anod build isl -v --loglevel DEBUG --enable-cleanup
    - name: Upload artifact 'gcc-dependencies-artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: gcc-dependencies-artifacts_ubuntu-22-04-arm
        path: out_artifacts/*
        retention-days: 1
  gnat_ubuntu-22-04-arm:
    needs:
    - gcc_dependencies_ubuntu-22-04-arm
    name: GNAT (ubuntu-22.04-arm)
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gcc-dependencies-artifacts'
      uses: actions/download-artifact@v4
      with:
        name: gcc-dependencies-artifacts_ubuntu-22-04-arm
        path: in_artifacts/
    - name: Build GNAT native
      run: python3 ./anod build gcc -v --loglevel DEBUG --enable-cleanup
    - name: Build GDB
      run: python3 ./anod build gdb -v --loglevel DEBUG --enable-cleanup
    - name: Package GNAT
      run: python3 ./anod build release_package --qualifier=package=gnat -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNAT
      run: python3 ./anod build release_github --qualifier=package=gnat -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnat-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnat-release-packages_ubuntu-22-04-arm
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gprbuild_ubuntu-22-04-arm:
    name: GPRbuild (ubuntu-22.04-arm)
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Build GPRbuild
      run: python3 ./anod build gprbuild -v --loglevel DEBUG --enable-cleanup
    - name: Package GPRbuild
      run: python3 ./anod build release_package --qualifier=package=gprbuild -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GPRbuild
      run: python3 ./anod build release_github --qualifier=package=gprbuild -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gprbuild-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gprbuild-release-packages_ubuntu-22-04-arm
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnat_cross_ubuntu-22-04-arm:
    strategy:
      fail-fast: false
      matrix:
        target:
        - arm-elf
        - aarch64-elf
        - riscv64-elf
        - x86_64-elf
        - avr-elf
        - xtensa-esp32-elf
    needs:
    - gcc_dependencies_ubuntu-22-04-arm
    name: GNAT Cross (ubuntu-22.04-arm)
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gcc-dependencies-artifacts'
      uses: actions/download-artifact@v4
      with:
        name: gcc-dependencies-artifacts_ubuntu-22-04-arm
        path: in_artifacts/
    - name: Build GNAT ${{ matrix.target }}
      run: python3 ./anod build gcc --target=${{ matrix.target }} -v --loglevel DEBUG --enable-cleanup
    - name: Build GDB ${{ matrix.target }}
      run: python3 ./anod build gdb --target=${{ matrix.target}} -v --loglevel DEBUG --enable-cleanup
    - name: Package GNAT ${{ matrix.target }}
      run: python3 ./anod build release_package --qualifier=package=gnat --target=${{ matrix.target }} -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNAT ${{ matrix.target }}
      run: python3 ./anod build release_github --qualifier=package=gnat --target=${{ matrix.target }} -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnat-release-packages-${{matrix.target}}'
      uses: actions/upload-artifact@v4
      with:
        name: gnat-release-packages-${{matrix.target}}_ubuntu-22-04-arm
        path: sbx/*/release_package*/install/*
  spark_ubuntu-22-04-arm:
    needs:
    - gprbuild_ubuntu-22-04-arm
    name: SPARK (ubuntu-22.04-arm)
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_ubuntu-22-04-arm
        path: in_artifacts/
    - name: Build SPARK
      run: python3 ./anod build spark2014 -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATprove
      run: python3 ./anod build release_package --qualifier=package=gnatprove -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATprove
      run: python3 ./anod build release_github --qualifier=package=gnatprove -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatprove-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatprove-release-packages_ubuntu-22-04-arm
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnatformat_ubuntu-22-04-arm:
    needs:
    - gprbuild_ubuntu-22-04-arm
    name: GNATformat (ubuntu-22.04-arm)
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_ubuntu-22-04-arm
        path: in_artifacts/
    - name: Build GNATformat
      run: python3 ./anod build gnatformat -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATformat
      run: python3 ./anod build release_package --qualifier=package=gnatformat -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATformat
      run: python3 ./anod build release_github --qualifier=package=gnatformat -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatformat-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatformat-release-packages_ubuntu-22-04-arm
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnatdoc_ubuntu-22-04-arm:
    needs:
    - gprbuild_ubuntu-22-04-arm
    name: GNATdoc (ubuntu-22.04-arm)
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_ubuntu-22-04-arm
        path: in_artifacts/
    - name: Build GNATdoc
      run: python3 ./anod build gnatdoc -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATdoc
      run: python3 ./anod build release_package --qualifier=package=gnatdoc -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATdoc
      run: python3 ./anod build release_github --qualifier=package=gnatdoc -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatdoc-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatdoc-release-packages_ubuntu-22-04-arm
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnattest_ubuntu-22-04-arm:
    needs:
    - gprbuild_ubuntu-22-04-arm
    name: GNATtest (ubuntu-22.04-arm)
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_ubuntu-22-04-arm
        path: in_artifacts/
    - name: Build GNATtest
      run: python3 ./anod build gnattest -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATtest
      run: python3 ./anod build release_package --qualifier=package=gnattest -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATtest
      run: python3 ./anod build release_github --qualifier=package=gnattest -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnattest-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnattest-release-packages_ubuntu-22-04-arm
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnatcoverage_ubuntu-22-04-arm:
    needs:
    - gprbuild_ubuntu-22-04-arm
    name: GNATcoverage (ubuntu-22.04-arm)
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_ubuntu-22-04-arm
        path: in_artifacts/
    - name: Build GNATcoverage
      run: python3 ./anod build gnatcov -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATcoverage
      run: python3 ./anod build release_package --qualifier=package=gnatcov -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATcoverage
      run: python3 ./anod build release_github --qualifier=package=gnatcov -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatcov-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatcov-release-packages_ubuntu-22-04-arm
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gcc_dependencies_macos-15-intel:
    name: GCC Dependencies (macos-15-intel)
    runs-on: macos-15-intel
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Build GMP
      run: python3 ./anod build gmp -v --loglevel DEBUG --enable-cleanup
    - name: Build MPFR
      run: python3 ./anod build mpfr -v --loglevel DEBUG --enable-cleanup
    - name: Build MPC
      run: python3 ./anod build mpc -v --loglevel DEBUG --enable-cleanup
    - name: Upload artifact 'gcc-dependencies-artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: gcc-dependencies-artifacts_macos-15-intel
        path: out_artifacts/*
        retention-days: 1
  gnat_macos-15-intel:
    needs:
    - gcc_dependencies_macos-15-intel
    name: GNAT (macos-15-intel)
    runs-on: macos-15-intel
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gcc-dependencies-artifacts'
      uses: actions/download-artifact@v4
      with:
        name: gcc-dependencies-artifacts_macos-15-intel
        path: in_artifacts/
    - name: Build GNAT native
      run: python3 ./anod build gcc -v --loglevel DEBUG --enable-cleanup
    - name: Build GDB
      run: python3 ./anod build gdb -v --loglevel DEBUG --enable-cleanup
    - name: Package GNAT
      run: python3 ./anod build release_package --qualifier=package=gnat -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNAT
      run: python3 ./anod build release_github --qualifier=package=gnat -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnat-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnat-release-packages_macos-15-intel
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gprbuild_macos-15-intel:
    name: GPRbuild (macos-15-intel)
    runs-on: macos-15-intel
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Build GPRbuild
      run: python3 ./anod build gprbuild -v --loglevel DEBUG --enable-cleanup
    - name: Package GPRbuild
      run: python3 ./anod build release_package --qualifier=package=gprbuild -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GPRbuild
      run: python3 ./anod build release_github --qualifier=package=gprbuild -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gprbuild-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gprbuild-release-packages_macos-15-intel
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnat_cross_macos-15-intel:
    strategy:
      fail-fast: false
      matrix:
        target:
        - arm-elf
        - aarch64-elf
        - riscv64-elf
        - x86_64-elf
        - avr-elf
        - xtensa-esp32-elf
    needs:
    - gcc_dependencies_macos-15-intel
    name: GNAT Cross (macos-15-intel)
    runs-on: macos-15-intel
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gcc-dependencies-artifacts'
      uses: actions/download-artifact@v4
      with:
        name: gcc-dependencies-artifacts_macos-15-intel
        path: in_artifacts/
    - name: Build GNAT ${{ matrix.target }}
      run: python3 ./anod build gcc --target=${{ matrix.target }} -v --loglevel DEBUG --enable-cleanup
    - name: Build GDB ${{ matrix.target }}
      run: python3 ./anod build gdb --target=${{ matrix.target}} -v --loglevel DEBUG --enable-cleanup
    - name: Package GNAT ${{ matrix.target }}
      run: python3 ./anod build release_package --qualifier=package=gnat --target=${{ matrix.target }} -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNAT ${{ matrix.target }}
      run: python3 ./anod build release_github --qualifier=package=gnat --target=${{ matrix.target }} -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnat-release-packages-${{matrix.target}}'
      uses: actions/upload-artifact@v4
      with:
        name: gnat-release-packages-${{matrix.target}}_macos-15-intel
        path: sbx/*/release_package*/install/*
  spark_macos-15-intel:
    needs:
    - gprbuild_macos-15-intel
    name: SPARK (macos-15-intel)
    runs-on: macos-15-intel
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_macos-15-intel
        path: in_artifacts/
    - name: Build SPARK
      run: python3 ./anod build spark2014 -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATprove
      run: python3 ./anod build release_package --qualifier=package=gnatprove -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATprove
      run: python3 ./anod build release_github --qualifier=package=gnatprove -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatprove-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatprove-release-packages_macos-15-intel
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnatformat_macos-15-intel:
    needs:
    - gprbuild_macos-15-intel
    name: GNATformat (macos-15-intel)
    runs-on: macos-15-intel
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_macos-15-intel
        path: in_artifacts/
    - name: Build GNATformat
      run: python3 ./anod build gnatformat -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATformat
      run: python3 ./anod build release_package --qualifier=package=gnatformat -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATformat
      run: python3 ./anod build release_github --qualifier=package=gnatformat -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatformat-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatformat-release-packages_macos-15-intel
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnatdoc_macos-15-intel:
    needs:
    - gprbuild_macos-15-intel
    name: GNATdoc (macos-15-intel)
    runs-on: macos-15-intel
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_macos-15-intel
        path: in_artifacts/
    - name: Build GNATdoc
      run: python3 ./anod build gnatdoc -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATdoc
      run: python3 ./anod build release_package --qualifier=package=gnatdoc -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATdoc
      run: python3 ./anod build release_github --qualifier=package=gnatdoc -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatdoc-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatdoc-release-packages_macos-15-intel
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnattest_macos-15-intel:
    needs:
    - gprbuild_macos-15-intel
    name: GNATtest (macos-15-intel)
    runs-on: macos-15-intel
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_macos-15-intel
        path: in_artifacts/
    - name: Build GNATtest
      run: python3 ./anod build gnattest -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATtest
      run: python3 ./anod build release_package --qualifier=package=gnattest -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATtest
      run: python3 ./anod build release_github --qualifier=package=gnattest -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnattest-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnattest-release-packages_macos-15-intel
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnatcoverage_macos-15-intel:
    needs:
    - gprbuild_macos-15-intel
    name: GNATcoverage (macos-15-intel)
    runs-on: macos-15-intel
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_macos-15-intel
        path: in_artifacts/
    - name: Build GNATcoverage
      run: python3 ./anod build gnatcov -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATcoverage
      run: python3 ./anod build release_package --qualifier=package=gnatcov -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATcoverage
      run: python3 ./anod build release_github --qualifier=package=gnatcov -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatcov-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatcov-release-packages_macos-15-intel
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gcc_dependencies_macos-15:
    name: GCC Dependencies (macos-15)
    runs-on: macos-15
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Build GMP
      run: python3 ./anod build gmp -v --loglevel DEBUG --enable-cleanup
    - name: Build MPFR
      run: python3 ./anod build mpfr -v --loglevel DEBUG --enable-cleanup
    - name: Build MPC
      run: python3 ./anod build mpc -v --loglevel DEBUG --enable-cleanup
    - name: Upload artifact 'gcc-dependencies-artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: gcc-dependencies-artifacts_macos-15
        path: out_artifacts/*
        retention-days: 1
  gnat_macos-15:
    needs:
    - gcc_dependencies_macos-15
    name: GNAT (macos-15)
    runs-on: macos-15
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gcc-dependencies-artifacts'
      uses: actions/download-artifact@v4
      with:
        name: gcc-dependencies-artifacts_macos-15
        path: in_artifacts/
    - name: Build GNAT native
      run: python3 ./anod build gcc -v --loglevel DEBUG --enable-cleanup
    - name: Build GDB
      run: python3 ./anod build gdb -v --loglevel DEBUG --enable-cleanup
    - name: Package GNAT
      run: python3 ./anod build release_package --qualifier=package=gnat -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNAT
      run: python3 ./anod build release_github --qualifier=package=gnat -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnat-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnat-release-packages_macos-15
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gprbuild_macos-15:
    name: GPRbuild (macos-15)
    runs-on: macos-15
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Build GPRbuild
      run: python3 ./anod build gprbuild -v --loglevel DEBUG --enable-cleanup
    - name: Package GPRbuild
      run: python3 ./anod build release_package --qualifier=package=gprbuild -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GPRbuild
      run: python3 ./anod build release_github --qualifier=package=gprbuild -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gprbuild-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gprbuild-release-packages_macos-15
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnat_cross_macos-15:
    strategy:
      fail-fast: false
      matrix:
        target:
        - arm-elf
        - aarch64-elf
        - riscv64-elf
        - x86_64-elf
        - avr-elf
        - xtensa-esp32-elf
    needs:
    - gcc_dependencies_macos-15
    name: GNAT Cross (macos-15)
    runs-on: macos-15
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gcc-dependencies-artifacts'
      uses: actions/download-artifact@v4
      with:
        name: gcc-dependencies-artifacts_macos-15
        path: in_artifacts/
    - name: Build GNAT ${{ matrix.target }}
      run: python3 ./anod build gcc --target=${{ matrix.target }} -v --loglevel DEBUG --enable-cleanup
    - name: Build GDB ${{ matrix.target }}
      run: python3 ./anod build gdb --target=${{ matrix.target}} -v --loglevel DEBUG --enable-cleanup
    - name: Package GNAT ${{ matrix.target }}
      run: python3 ./anod build release_package --qualifier=package=gnat --target=${{ matrix.target }} -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNAT ${{ matrix.target }}
      run: python3 ./anod build release_github --qualifier=package=gnat --target=${{ matrix.target }} -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnat-release-packages-${{matrix.target}}'
      uses: actions/upload-artifact@v4
      with:
        name: gnat-release-packages-${{matrix.target}}_macos-15
        path: sbx/*/release_package*/install/*
  spark_macos-15:
    needs:
    - gprbuild_macos-15
    name: SPARK (macos-15)
    runs-on: macos-15
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_macos-15
        path: in_artifacts/
    - name: Build SPARK
      run: python3 ./anod build spark2014 -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATprove
      run: python3 ./anod build release_package --qualifier=package=gnatprove -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATprove
      run: python3 ./anod build release_github --qualifier=package=gnatprove -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatprove-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatprove-release-packages_macos-15
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnatformat_macos-15:
    needs:
    - gprbuild_macos-15
    name: GNATformat (macos-15)
    runs-on: macos-15
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_macos-15
        path: in_artifacts/
    - name: Build GNATformat
      run: python3 ./anod build gnatformat -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATformat
      run: python3 ./anod build release_package --qualifier=package=gnatformat -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATformat
      run: python3 ./anod build release_github --qualifier=package=gnatformat -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatformat-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatformat-release-packages_macos-15
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnatdoc_macos-15:
    needs:
    - gprbuild_macos-15
    name: GNATdoc (macos-15)
    runs-on: macos-15
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_macos-15
        path: in_artifacts/
    - name: Build GNATdoc
      run: python3 ./anod build gnatdoc -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATdoc
      run: python3 ./anod build release_package --qualifier=package=gnatdoc -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATdoc
      run: python3 ./anod build release_github --qualifier=package=gnatdoc -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatdoc-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatdoc-release-packages_macos-15
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnattest_macos-15:
    needs:
    - gprbuild_macos-15
    name: GNATtest (macos-15)
    runs-on: macos-15
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_macos-15
        path: in_artifacts/
    - name: Build GNATtest
      run: python3 ./anod build gnattest -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATtest
      run: python3 ./anod build release_package --qualifier=package=gnattest -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATtest
      run: python3 ./anod build release_github --qualifier=package=gnattest -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnattest-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnattest-release-packages_macos-15
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gnatcoverage_macos-15:
    needs:
    - gprbuild_macos-15
    name: GNATcoverage (macos-15)
    runs-on: macos-15
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install packages with Homebrew
      run: |-
        brew install texinfo
        brew install autoconf
        brew install automake
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_macos-15
        path: in_artifacts/
    - name: Build GNATcoverage
      run: python3 ./anod build gnatcov -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATcoverage
      run: python3 ./anod build release_package --qualifier=package=gnatcov -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATcoverage
      run: python3 ./anod build release_github --qualifier=package=gnatcov -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatcov-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatcov-release-packages_macos-15
        path: sbx/*/release_package*/install/*
        retention-days: 5
  gcc_dependencies_windows-2022:
    name: GCC Dependencies (windows-2022)
    runs-on: windows-2022
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          base-devel
          git
          rsync
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Build GMP
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gmp -v --loglevel DEBUG --enable-cleanup
    - name: Build MPFR
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build mpfr -v --loglevel DEBUG --enable-cleanup
    - name: Build MPC
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build mpc -v --loglevel DEBUG --enable-cleanup
    - name: Build ISL
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build isl -v --loglevel DEBUG --enable-cleanup
    - name: Upload artifact 'gcc-dependencies-artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: gcc-dependencies-artifacts_windows-2022
        path: C:/aaa/GNAT-FSF-builds/out_artifacts/*
        retention-days: 1
  gnat_windows-2022:
    needs:
    - gcc_dependencies_windows-2022
    name: GNAT (windows-2022)
    runs-on: windows-2022
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          base-devel
          git
          rsync
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Download artifact 'gcc-dependencies-artifacts'
      uses: actions/download-artifact@v4
      with:
        name: gcc-dependencies-artifacts_windows-2022
        path: C:/aaa/GNAT-FSF-builds/in_artifacts/
    - name: Build GNAT native
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gcc -v --loglevel DEBUG --enable-cleanup
    - name: Build GDB
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gdb -v --loglevel DEBUG --enable-cleanup
    - name: Package GNAT
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnat -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNAT
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_github --qualifier=package=gnat -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnat-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnat-release-packages_windows-2022
        path: C:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5
  gprbuild_windows-2022:
    name: GPRbuild (windows-2022)
    runs-on: windows-2022
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          base-devel
          git
          rsync
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Build GPRbuild
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gprbuild -v --loglevel DEBUG --enable-cleanup
    - name: Package GPRbuild
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gprbuild -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GPRbuild
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_github --qualifier=package=gprbuild -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gprbuild-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gprbuild-release-packages_windows-2022
        path: C:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5
  gnat_cross_windows-2022:
    strategy:
      fail-fast: false
      matrix:
        target:
        - arm-elf
        - aarch64-elf
        - riscv64-elf
        - x86_64-elf
        - avr-elf
        - xtensa-esp32-elf
    needs:
    - gcc_dependencies_windows-2022
    name: GNAT Cross (windows-2022)
    runs-on: windows-2022
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          base-devel
          git
          rsync
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Download artifact 'gcc-dependencies-artifacts'
      uses: actions/download-artifact@v4
      with:
        name: gcc-dependencies-artifacts_windows-2022
        path: C:/aaa/GNAT-FSF-builds/in_artifacts/
    - name: Build GNAT ${{ matrix.target }}
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gcc --target=${{ matrix.target }} -v --loglevel DEBUG --enable-cleanup
    - name: Build GDB ${{ matrix.target }}
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gdb --target=${{ matrix.target}} -v --loglevel DEBUG --enable-cleanup
    - name: Package GNAT ${{ matrix.target }}
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnat --target=${{ matrix.target }} -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNAT ${{ matrix.target }}
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_github --qualifier=package=gnat --target=${{ matrix.target }} -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnat-release-packages-${{matrix.target}}'
      uses: actions/upload-artifact@v4
      with:
        name: gnat-release-packages-${{matrix.target}}_windows-2022
        path: C:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
  spark_windows-2022:
    needs:
    - gprbuild_windows-2022
    name: SPARK (windows-2022)
    runs-on: windows-2022
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          base-devel
          git
          rsync
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_windows-2022
        path: C:/aaa/GNAT-FSF-builds/in_artifacts/
    - name: Build SPARK
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build spark2014 -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATprove
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnatprove -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATprove
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_github --qualifier=package=gnatprove -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatprove-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatprove-release-packages_windows-2022
        path: C:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5
  gnatformat_windows-2022:
    needs:
    - gprbuild_windows-2022
    name: GNATformat (windows-2022)
    runs-on: windows-2022
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          base-devel
          git
          rsync
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_windows-2022
        path: C:/aaa/GNAT-FSF-builds/in_artifacts/
    - name: Build GNATformat
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gnatformat -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATformat
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnatformat -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATformat
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_github --qualifier=package=gnatformat -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatformat-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatformat-release-packages_windows-2022
        path: C:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5
  gnatdoc_windows-2022:
    needs:
    - gprbuild_windows-2022
    name: GNATdoc (windows-2022)
    runs-on: windows-2022
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          base-devel
          git
          rsync
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_windows-2022
        path: C:/aaa/GNAT-FSF-builds/in_artifacts/
    - name: Build GNATdoc
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gnatdoc -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATdoc
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnatdoc -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATdoc
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_github --qualifier=package=gnatdoc -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatdoc-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatdoc-release-packages_windows-2022
        path: C:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5
  gnattest_windows-2022:
    needs:
    - gprbuild_windows-2022
    name: GNATtest (windows-2022)
    runs-on: windows-2022
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          base-devel
          git
          rsync
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_windows-2022
        path: C:/aaa/GNAT-FSF-builds/in_artifacts/
    - name: Build GNATtest
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gnattest -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATtest
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnattest -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATtest
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_github --qualifier=package=gnattest -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnattest-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnattest-release-packages_windows-2022
        path: C:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5
  gnatcoverage_windows-2022:
    needs:
    - gprbuild_windows-2022
    name: GNATcoverage (windows-2022)
    runs-on: windows-2022
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          base-devel
          git
          rsync
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Download artifact 'gprbuild-release-packages'
      uses: actions/download-artifact@v4
      with:
        name: gprbuild-release-packages_windows-2022
        path: C:/aaa/GNAT-FSF-builds/in_artifacts/
    - name: Build GNATcoverage
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gnatcov -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATcoverage
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnatcov -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATcoverage
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_github --qualifier=package=gnatcov -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatcov-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatcov-release-packages_windows-2022
        path: C:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5
